### ISSUE TITLE
Display facing in GUI

### ISSUE THREAD

**Issue by UhoMazino** [GlodBlock/BetterP2P#1]
I think it should display forge direction for p2p in GUI position string, because you can have more than one p2p in the same position

**Comment by GlodBlock** [comment]
added now https://github.com/GlodBlock/BetterP2P/commit/1d37f1b0fd1bd5e0d33935e75c772d2f4cb6e75a
![2022-01-30_19 22 31](https://user-images.githubusercontent.com/60341015/151697529-9a881eb9-a450-4e6e-ba76-8c77e356dd49.png)
