### ISSUE TITLE
Crash when clicked on a controller

### ISSUE THREAD

**Issue by foxwhite25** [GlodBlock/BetterP2P#3]
It's on GTNH with version 2.1.2.3
Reproduce step: Right click on a ME controller
[crash-2022-03-24_22.13.35-client.txt](https://github.com/GlodBlock/BetterP2P/files/8342287/crash-2022-03-24_22.13.35-client.txt)

**Comment by GlodBlock** [comment]
it has been fixed in dev now. you can download the fixed jar in http://jenkins.usrv.eu:8080/job/BetterP2P/

**Comment by foxwhite25** [comment]
Nice, thanks
